services:
  - type: web
    name: metabase-web
    env: docker
    repo: https://github.com/polarsource/metabase.git
    plan: 1c-2g
    region: ohio
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase-db
          property: connectionString
      - key: MB_SESSION_SECRET_KEY
        sync: false
databases:
  - name: metabase-db
    region: ohio
    plan: 0.5c-1g
    databaseName: metabasedb
    ipAllowList: [] # only allow internal connections
