services:
  - type: web
    name: metabase-web
    env: docker
    repo: https://github.com/polarsource/metabase.git # optional
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    region: ohio
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase-db
          property: connectionString
databases:
  - name: metabase-db
    region: ohio
    databaseName: metabasedb
    ipAllowList: [] # only allow internal connections
